### ISSUE TITLE
Can you provide more details on downloading the relevant datasets for this project?

### ISSUE THREAD

**Issue by lmllmllm** [Neoyanghc/HiGRN#1]
Can you provide more details on downloading the relevant datasets for this project?

**Comment by Neoyanghc** [comment]
Thanks for your question. You can download the datasets from NOAA  https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html， the instructions are also in the NOAA website

**Comment by Fccccccc** [comment]
> 您能否提供有关下载此项目相关数据集的更多详细信息？

你好，请问你的代码运行成功了吗？
