### ISSUE TITLE
Hi, is there some part of the code missing, perhaps my problem is not running successfully, can I ask you a question privately?

### ISSUE THREAD

**Issue by Fccccccc** [Neoyanghc/HiGRN#2]
Hi, is there some part of the code missing, perhaps my problem is not running successfully, can I ask you a question privately? I really need your help, my email is: fangc0729@163.com or 23cfang@stu.edu.cn

**Comment by Neoyanghc** [comment]
thanks for question，you can put your problem here for public use.

**Comment by Fccccccc** [comment]
> 感谢您的提问，您可以将您的问题放在这里供公众使用。或发送到我的电子邮件。[neoyang@tongji.edu.cn](mailto:neoyang@tongji.edu.cn)

感谢回答，以经向您发邮件请教。

**Comment by Fccccccc** [comment]
> thanks for question，you can put your problem here for public use. or send to my email. [neoyang@tongji.edu.cn](mailto:neoyang@tongji.edu.cn)

感谢您的回答，已经向您发送邮件请教。

**Comment by Fccccccc** [comment]
您好，打扰您了，请问您收到邮件了嘛，主要问题就是nc文件的处理和输入到网络，以及详细的数据集信息。
